### ISSUE TITLE
The program isn't compatible with Linux

### ISSUE THREAD

**Issue by guillaumeki** [mnederkorn/CoReS#2]
The program isn't compatible with Linux for the following reasons : 
- In line 320 of cores.py, there is a regex : 
`.(@\d+(?:-\d+)*_@\d+(?:-\d+)*) = 1\r\n`
The problem here is that there is no carriage return on Linux. So, there is an infinite loop.
To solve this problem, I propose the following regex : 
`.(@\d+(?:-\d+)*_@\d+(?:-\d+)*) = 1\r{0,1}\n`
With this fix, the program can compute the core in Ubuntu 16.04.

- the other problem is about paths : the separator for the folders on Linux is "/" and not "\" - the images are not the right folder because of that.
For example, in line 181 of cores.py : 
`target_path = os.path.dirname(os.path.realpath(__file__))+"\\images\\"+datetime.now().strftime('%Y-%m-%d-%H-%M-%S-%f')`
should be replaced on Linux with : 
`target_path = os.path.dirname(os.path.realpath(__file__))+"/images/"+datetime.now().strftime('%Y-%m-%d-%H-%M-%S-%f')`
I think the second form also functions on windows but I'm not sure of that.

Thank you for this program.

**Comment by mnederkorn** [comment]
Should be resolved as of a96bfcc6afdfc36f431bbf665e19da7d99686a13
